apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mdp-821-api-12
  description: API test mdp-821 folder level test
  labels:
    access: internal
  tags:
    - recommended
spec:
  type: platform domain
  lifecycle: deprecated
  owner: devportal-tester
  definition: |
    {
      "openapi": "3.1.0"
      "info": {
        "version": "2022-01-01"
        "title": "mdp-821-api-12"
      }
    }
